### ISSUE TITLE
Wooden and stone whetstones unfunctional, with onlytool and onlylowertiers set to false

### ISSUE THREAD

**Issue by Darkmega18** [Bakabreak/Whetstones#1]
**Version info**
- Whetstones: "whetstones-1.0.0-forge-mc1.19.jar"
- Minecraft: "1.19.2"

**Describe the bug**
Wooden and stone whetstones either don't take into consideration the configurations for any item and only lower tier or they're broken entirely.

Basically, I'm trying to test the use of the whetstones. but the wooden one and stone ones are completely unuseable. even on items which are actually stone or wooden tier. And despite my configs being set "onlyTools = false" and "onlyLowerTiers = false" they are ineffective on armors etc until I get to iron grade atleast.

**To Reproduce**
it's just how it's working. match configs. configure durability amounts lower to rebalance, then try to repair leather grade armor or stone and wood grade tools with a wooden or stone whetstone. only tiers iron and above actually work.

**Comment by Bakabreak** [comment]
Thank you for letting me know, I have fixed the problem and the stone and wooden whetstones should now work as intended.
